"""User added status,  removed achieved

Revision ID: 5a3d7fb706e8
Revises: ee816a6604d4
Create Date: 2019-10-21 00:45:40.408613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3d7fb706e8'
down_revision = 'ee816a6604d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('status', sa.String(length=30), nullable=True))
    op.drop_column('route', 'achieved')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('achieved', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('route', 'status')
    # ### end Alembic commands ###
